// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/proto/mco.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_api_proto_mco_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_api_proto_mco_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{1}
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestroyClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyClusterRequest) Reset() {
	*x = DestroyClusterRequest{}
	mi := &file_api_proto_mco_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyClusterRequest) ProtoMessage() {}

func (x *DestroyClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyClusterRequest.ProtoReflect.Descriptor instead.
func (*DestroyClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_api_proto_mco_proto protoreflect.FileDescriptor

const file_api_proto_mco_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/mco.proto\x12\x04mkit\"*\n" +
	"\x14CreateClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\n" +
	"LogMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x15DestroyClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\x8c\x01\n" +
	"\x06Daemon\x12?\n" +
	"\rCreateCluster\x12\x1a.mkit.CreateClusterRequest\x1a\x10.mkit.LogMessage0\x01\x12A\n" +
	"\x0eDestroyCluster\x12\x1b.mkit.DestroyClusterRequest\x1a\x10.mkit.LogMessage0\x01B2Z0github.com/openshift-eng/machine-config-mkit/apib\x06proto3"

var (
	file_api_proto_mco_proto_rawDescOnce sync.Once
	file_api_proto_mco_proto_rawDescData []byte
)

func file_api_proto_mco_proto_rawDescGZIP() []byte {
	file_api_proto_mco_proto_rawDescOnce.Do(func() {
		file_api_proto_mco_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mco_proto_rawDesc), len(file_api_proto_mco_proto_rawDesc)))
	})
	return file_api_proto_mco_proto_rawDescData
}

var file_api_proto_mco_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_mco_proto_goTypes = []any{
	(*CreateClusterRequest)(nil),  // 0: mkit.CreateClusterRequest
	(*LogMessage)(nil),            // 1: mkit.LogMessage
	(*DestroyClusterRequest)(nil), // 2: mkit.DestroyClusterRequest
}
var file_api_proto_mco_proto_depIdxs = []int32{
	0, // 0: mkit.Daemon.CreateCluster:input_type -> mkit.CreateClusterRequest
	2, // 1: mkit.Daemon.DestroyCluster:input_type -> mkit.DestroyClusterRequest
	1, // 2: mkit.Daemon.CreateCluster:output_type -> mkit.LogMessage
	1, // 3: mkit.Daemon.DestroyCluster:output_type -> mkit.LogMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_mco_proto_init() }
func file_api_proto_mco_proto_init() {
	if File_api_proto_mco_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mco_proto_rawDesc), len(file_api_proto_mco_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mco_proto_goTypes,
		DependencyIndexes: file_api_proto_mco_proto_depIdxs,
		MessageInfos:      file_api_proto_mco_proto_msgTypes,
	}.Build()
	File_api_proto_mco_proto = out.File
	file_api_proto_mco_proto_goTypes = nil
	file_api_proto_mco_proto_depIdxs = nil
}
