// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.23.4
// source: api/proto/mco.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClusterState int32

const (
	ClusterState_UNKNOWN  ClusterState = 0
	ClusterState_CREATING ClusterState = 1
	ClusterState_CREATED  ClusterState = 2
	ClusterState_DELETING ClusterState = 3
	ClusterState_DELETED  ClusterState = 4
)

// Enum value maps for ClusterState.
var (
	ClusterState_name = map[int32]string{
		0: "UNKNOWN",
		1: "CREATING",
		2: "CREATED",
		3: "DELETING",
		4: "DELETED",
	}
	ClusterState_value = map[string]int32{
		"UNKNOWN":  0,
		"CREATING": 1,
		"CREATED":  2,
		"DELETING": 3,
		"DELETED":  4,
	}
)

func (x ClusterState) Enum() *ClusterState {
	p := new(ClusterState)
	*p = x
	return p
}

func (x ClusterState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClusterState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_mco_proto_enumTypes[0].Descriptor()
}

func (ClusterState) Type() protoreflect.EnumType {
	return &file_api_proto_mco_proto_enumTypes[0]
}

func (x ClusterState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClusterState.Descriptor instead.
func (ClusterState) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{0}
}

type CreateClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClusterRequest) Reset() {
	*x = CreateClusterRequest{}
	mi := &file_api_proto_mco_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClusterRequest) ProtoMessage() {}

func (x *CreateClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClusterRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type ClusterStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ClusterState           `protobuf:"varint,1,opt,name=state,proto3,enum=kit.ClusterState" json:"state,omitempty"`
	Kubeconfig    string                 `protobuf:"bytes,2,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_api_proto_mco_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{1}
}

func (x *ClusterStatus) GetState() ClusterState {
	if x != nil {
		return x.State
	}
	return ClusterState_UNKNOWN
}

func (x *ClusterStatus) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

type DestroyClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyClusterRequest) Reset() {
	*x = DestroyClusterRequest{}
	mi := &file_api_proto_mco_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyClusterRequest) ProtoMessage() {}

func (x *DestroyClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyClusterRequest.ProtoReflect.Descriptor instead.
func (*DestroyClusterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{2}
}

func (x *DestroyClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetClusterKubeConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       bool                   `protobuf:"varint,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterKubeConfigRequest) Reset() {
	*x = GetClusterKubeConfigRequest{}
	mi := &file_api_proto_mco_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterKubeConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterKubeConfigRequest) ProtoMessage() {}

func (x *GetClusterKubeConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterKubeConfigRequest.ProtoReflect.Descriptor instead.
func (*GetClusterKubeConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{3}
}

func (x *GetClusterKubeConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetClusterKubeConfigRequest) GetContent() bool {
	if x != nil {
		return x.Content
	}
	return false
}

type GetClusterKubeConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterKubeConfigResponse) Reset() {
	*x = GetClusterKubeConfigResponse{}
	mi := &file_api_proto_mco_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterKubeConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterKubeConfigResponse) ProtoMessage() {}

func (x *GetClusterKubeConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_mco_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterKubeConfigResponse.ProtoReflect.Descriptor instead.
func (*GetClusterKubeConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_mco_proto_rawDescGZIP(), []int{4}
}

func (x *GetClusterKubeConfigResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetClusterKubeConfigResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_api_proto_mco_proto protoreflect.FileDescriptor

const file_api_proto_mco_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/mco.proto\x12\x03kit\"F\n" +
	"\x14CreateClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"X\n" +
	"\rClusterStatus\x12'\n" +
	"\x05state\x18\x01 \x01(\x0e2\x11.kit.ClusterStateR\x05state\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x02 \x01(\tR\n" +
	"kubeconfig\"+\n" +
	"\x15DestroyClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x1bGetClusterKubeConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\bR\acontent\"L\n" +
	"\x1cGetClusterKubeConfigResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent*Q\n" +
	"\fClusterState\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bCREATING\x10\x01\x12\v\n" +
	"\aCREATED\x10\x02\x12\f\n" +
	"\bDELETING\x10\x03\x12\v\n" +
	"\aDELETED\x10\x042\xeb\x01\n" +
	"\x06Daemon\x12@\n" +
	"\rCreateCluster\x12\x19.kit.CreateClusterRequest\x1a\x12.kit.ClusterStatus0\x01\x12B\n" +
	"\x0eDestroyCluster\x12\x1a.kit.DestroyClusterRequest\x1a\x12.kit.ClusterStatus0\x01\x12[\n" +
	"\x14GetClusterKubeConfig\x12 .kit.GetClusterKubeConfigRequest\x1a!.kit.GetClusterKubeConfigResponseB=Z;github.com/openshift-eng/kubernetes-integration-testing/apib\x06proto3"

var (
	file_api_proto_mco_proto_rawDescOnce sync.Once
	file_api_proto_mco_proto_rawDescData []byte
)

func file_api_proto_mco_proto_rawDescGZIP() []byte {
	file_api_proto_mco_proto_rawDescOnce.Do(func() {
		file_api_proto_mco_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_mco_proto_rawDesc), len(file_api_proto_mco_proto_rawDesc)))
	})
	return file_api_proto_mco_proto_rawDescData
}

var file_api_proto_mco_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_mco_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_mco_proto_goTypes = []any{
	(ClusterState)(0),                    // 0: kit.ClusterState
	(*CreateClusterRequest)(nil),         // 1: kit.CreateClusterRequest
	(*ClusterStatus)(nil),                // 2: kit.ClusterStatus
	(*DestroyClusterRequest)(nil),        // 3: kit.DestroyClusterRequest
	(*GetClusterKubeConfigRequest)(nil),  // 4: kit.GetClusterKubeConfigRequest
	(*GetClusterKubeConfigResponse)(nil), // 5: kit.GetClusterKubeConfigResponse
}
var file_api_proto_mco_proto_depIdxs = []int32{
	0, // 0: kit.ClusterStatus.state:type_name -> kit.ClusterState
	1, // 1: kit.Daemon.CreateCluster:input_type -> kit.CreateClusterRequest
	3, // 2: kit.Daemon.DestroyCluster:input_type -> kit.DestroyClusterRequest
	4, // 3: kit.Daemon.GetClusterKubeConfig:input_type -> kit.GetClusterKubeConfigRequest
	2, // 4: kit.Daemon.CreateCluster:output_type -> kit.ClusterStatus
	2, // 5: kit.Daemon.DestroyCluster:output_type -> kit.ClusterStatus
	5, // 6: kit.Daemon.GetClusterKubeConfig:output_type -> kit.GetClusterKubeConfigResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_mco_proto_init() }
func file_api_proto_mco_proto_init() {
	if File_api_proto_mco_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_mco_proto_rawDesc), len(file_api_proto_mco_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_mco_proto_goTypes,
		DependencyIndexes: file_api_proto_mco_proto_depIdxs,
		EnumInfos:         file_api_proto_mco_proto_enumTypes,
		MessageInfos:      file_api_proto_mco_proto_msgTypes,
	}.Build()
	File_api_proto_mco_proto = out.File
	file_api_proto_mco_proto_goTypes = nil
	file_api_proto_mco_proto_depIdxs = nil
}
